name: game_launcher
description: "A klondike game."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0

  klondike_package:
    path: ../klondike_package

  brick_breaker_package:
    path: ../brick_breaker_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
